export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR'
export const GET_ARTICLES_BY_ID = 'GET_ARTICLES';
export const GET_ARTICLES_BY_ID_ERROR = 'GET_ARTICLES_ERROR'
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR'
