export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR'
export const GET_ARTICLES_BY_ID = 'GET_ARTICLES';
export const GET_ARTICLES_BY_ID_ERROR = 'GET_ARTICLES_ERROR'
